"use client";
import {useEffect,useState} from "react";
import {ArrowLeft,ArrowRight,Download,Search,RefreshCw,X} from "lucide-react";
import {Bar,BarChart,ResponsiveContainer,Tooltip,XAxis,YAxis,CartesianGrid} from "recharts";
import {Button} from "@/components/ui/button";
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from "@/components/ui/table";

type Filters={dataset_id:string;study:string;disease:string;gene:string;chromosome:string;variant_type:string;q:string;min_samples:string;page:string;page_size:string;sort:string;heatmap_page:string};
type Gene={id:number;symbol:string;gene_type:string;mutated_samples:number;eligible_samples:number;frequency:number|null;variants:number;observed_chromosomes:string[]};
type Variant={variant_id:number;assembly:string;chromosome:string;position:number;ref:string;alt:string;variant_type:string;genes:string[];consequences:string[];samples:number;vaf_min:number|null;vaf_max:number|null;vaf_measured:number};
type Count={label:string;count:number};
type Result={dataset:{id:number;name:string;sha256:string;retrieved_at:string;is_fixture:boolean;source:string;url:string};method:string;computed_at:string;code_revision:string;filters:Record<string,string|number>;limitations:string[];options:{studies:[string,string][];diseases:[string,string][];genes:string[];chromosomes:string[];variant_types:string[]};summary:{eligible_samples:number;mutated_samples:number;variants:number;observations:number;affected_genes:number;missing_vaf:number};genes:Gene[];variants:{items:Variant[];total:number;page:number;page_size:number};chromosomes:Count[];variant_types:Count[];vaf_histogram:Count[];heatmap:{page:number;page_size:number;total:number;samples:string[];rows:{symbol:string;values:(number|null)[]}[]}};
const initial:Filters={dataset_id:"",study:"",disease:"",gene:"",chromosome:"",variant_type:"",q:"",min_samples:"0",page:"1",page_size:"25",sort:"position",heatmap_page:"1"};
const percent=(n:number|null)=>n===null?"Not estimable":(n*100).toFixed(1)+"%";
const locus=(v:Variant)=>v.chromosome+":"+v.position+":"+v.ref+">"+v.alt;
const tipStyle={background:"var(--surface)",color:"var(--ink)",border:"1px solid var(--line)",borderRadius:6,fontSize:12};
export function Genomics({mode,datasets}:{mode:"Genomics"|"Gene explorer"|"Variant explorer";datasets:{id:number;name:string;version:string}[]}){
 const [filters,setFilters]=useState<Filters>(initial);
 const [draft,setDraft]=useState<Filters>(initial);
 const [data,setData]=useState<Result|null>(null);
 const [busy,setBusy]=useState(true);
 const [error,setError]=useState<string|null>(null);
 const [retry,setRetry]=useState(0);
 const [selectedGene,setSelectedGene]=useState<string|null>(null);
 const [selectedVariant,setSelectedVariant]=useState<number|null>(null);
 useEffect(()=>{
  const controller=new AbortController();setBusy(true);setError(null);setData(null);setSelectedGene(null);setSelectedVariant(null);
  const query=new URLSearchParams();Object.entries(filters).forEach(([k,v])=>{if(v)query.set(k,v);});
  fetch("/api/genomics?"+query,{cache:"no-store",signal:controller.signal}).then(async response=>{
   const body=await response.json();if(!response.ok)throw new Error(body.detail||"Genomic results unavailable.");return body;
  }).then(body=>{if(!controller.signal.aborted)setData(body);}).catch(e=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:"Genomic results unavailable.");}).finally(()=>{if(!controller.signal.aborted)setBusy(false);});
  return()=>controller.abort();
 },[filters,retry]);
 function apply(next:Filters){setDraft(next);setFilters({...next});}
 function update(key:keyof Filters,value:string){setDraft({...draft,[key]:value});}
 function drill(symbol:string){apply({...filters,gene:symbol,page:"1",heatmap_page:"1"});}
 function exportResult(){if(!data)return;const payload={kind:"descriptive_genomics",...data,export_scope:"Summary and distributions cover all filtered results; variant and heatmap rows contain the indicated page only."};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download="pharmagenome-genomics-dataset-"+data.dataset.id+".json";a.click();URL.revokeObjectURL(url);}
 const gene=data?.genes.find(g=>g.symbol===selectedGene);
 const variant=data?.variants.items.find(v=>v.variant_id===selectedVariant);
 return <div className="genomics">
 <section className="panel filter-panel" aria-label="Genomic filters"><form onSubmit={e=>{e.preventDefault();apply({...draft,page:"1",heatmap_page:"1"});}}>
 <div className="filter-grid">
 <label className="wide-filter">Dataset snapshot<select value={draft.dataset_id} onChange={e=>{setDraft({...initial,dataset_id:e.target.value});}}><option value="">Latest completed snapshot</option>{datasets.map(d=><option key={d.id} value={d.id}>{d.name+" · "+d.version.slice(0,8)}</option>)}</select></label>
 <label>Study<select value={draft.study} onChange={e=>update("study",e.target.value)}><option value="">All profiled studies</option>{data?.options.studies.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>
 <label>Disease<select value={draft.disease} onChange={e=>update("disease",e.target.value)}><option value="">All cohort diseases</option>{data?.options.diseases.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>
 <label>Gene<select value={draft.gene} onChange={e=>update("gene",e.target.value)}><option value="">All imported genes</option>{data?.options.genes.map(g=><option key={g}>{g}</option>)}</select></label>
 <label>Chromosome<select value={draft.chromosome} onChange={e=>update("chromosome",e.target.value)}><option value="">All chromosomes</option>{data?.options.chromosomes.map(c=><option key={c}>{c}</option>)}</select></label>
 <label>Variant type<select value={draft.variant_type} onChange={e=>update("variant_type",e.target.value)}><option value="">All imported types</option>{data?.options.variant_types.map(t=><option key={t}>{t}</option>)}</select></label>
 <label>Minimum mutated samples<input type="number" min="0" max="1000000" required value={draft.min_samples} onChange={e=>update("min_samples",e.target.value)}/><small>Gene ranking and matrix only</small></label>
 </div><div className="filter-actions"><label className="search-field"><Search size={17}/><input aria-label="Search gene or variant locus" placeholder="Search gene or locus, e.g. TP53 or 17:7577123" maxLength={80} value={draft.q} onChange={e=>update("q",e.target.value)}/></label><Button type="submit" disabled={busy}>Apply filters</Button><Button type="button" variant="outline" onClick={()=>apply(initial)} disabled={busy}>Reset</Button></div><p className="filter-note">Apply filters to update results. Gene, locus and variant filters keep the eligible cohort denominator.</p>
 </form></section>
 {busy&&<section className="panel analysis-state" role="status"><RefreshCw size={22} className="spin"/><h2>Computing your cohort view…</h2><p>Reading the selected snapshot and counting distinct profiled samples.</p></section>}
 {error&&<section className="panel analysis-state" role="alert"><h2>Genomic results unavailable</h2><p>{error}</p><Button variant="outline" onClick={()=>setRetry(retry+1)}>Retry analysis</Button></section>}
 {data&&!busy&&<><div className="analysis-context"><div><strong>{data.dataset.name}</strong><span>{data.dataset.is_fixture?"Synthetic development fixture":"Public source data"} · {data.method}</span><span>Applied: gene {filters.gene||"all"} · chromosome {filters.chromosome||"all"} · type {filters.variant_type||"all"} · search {filters.q||"none"}</span></div><Button variant="outline" onClick={exportResult}><Download size={15}/>Export analysis JSON</Button></div>
 <section className="inventory analysis-inventory" aria-label="Filtered genomic inventory">{[["Eligible samples",data.summary.eligible_samples],["Matching samples",data.summary.mutated_samples],["Unique variants",data.summary.variants],["Affected genes",data.summary.affected_genes],["Observations",data.summary.observations]].map(([name,value])=><div key={name}><span>{name}</span><strong>{value.toLocaleString()}</strong></div>)}</section>
 {data.summary.eligible_samples===0&&<p className="cohort-warning" role="status">No eligible samples in this cohort. Mutation frequencies are not estimable.</p>}
 {mode==="Genomics"&&<><div className="genomic-chart-grid"><section className="panel"><div className="section-title"><div><h2>Observed SNV frequency</h2><p>Distinct matching samples / gene-eligible profiled samples</p></div></div>{data.genes.length?<><div className="frequency-chart"><ResponsiveContainer width="100%" height="100%"><BarChart accessibilityLayer data={data.genes.map(g=>({...g,percentage:g.frequency===null?null:Number((g.frequency*100).toFixed(2))}))} layout="vertical" margin={{left:0,right:15,top:10,bottom:0}}><CartesianGrid horizontal={false} stroke="var(--line)"/><XAxis type="number" domain={[0,100]} unit="%" tick={{fill:"var(--muted)",fontSize:10}}/><YAxis type="category" dataKey="symbol" width={64} tick={{fill:"var(--ink)",fontSize:11}} tickLine={false}/><Tooltip contentStyle={tipStyle}/><Bar name="Observed frequency (%)" dataKey="percentage" fill="var(--accent)" radius={[0,3,3,0]} isAnimationActive={false}/></BarChart></ResponsiveContainer></div><div className="gene-shortcuts" aria-label="Filter by ranked gene">{data.genes.map(g=><button key={g.id} onClick={()=>drill(g.symbol)}>{g.symbol}<span>{percent(g.frequency)}</span></button>)}</div></>:<p className="body-copy">No genes meet the ranking filter. Lower the minimum or reset filters.</p>}</section>
 <section className="panel"><h2>Variant composition</h2><p className="body-copy">Counts use distinct variant identities. Only imported types are available.</p><dl className="composition">{data.variant_types.length?data.variant_types.map(t=><div key={t.label}><dt>{t.label}</dt><dd>{t.count.toLocaleString()}</dd></div>):<div><dt>Matching variants</dt><dd>0</dd></div>}</dl><h3 className="chart-subtitle">Chromosomal distribution</h3><p className="chart-caption">Counts, not length-normalized density. Select a chromosome to filter.</p><div className="chromosome-buttons">{data.chromosomes.map(c=><button key={c.label} onClick={()=>apply({...filters,chromosome:c.label,page:"1",heatmap_page:"1"})}><span>Chr {c.label}</span><strong>{c.count}</strong></button>)}</div></section></div>
 <section className="panel vaf-panel"><div><h2>Tumour VAF distribution</h2><p className="body-copy">Alternate reads / total tumour reads, per sample–variant observation. This is not population allele frequency. Bins include their lower bound; the final bin includes 100%.</p><p className="chart-caption">{data.summary.missing_vaf} observations have no usable VAF.</p></div><div className="histogram"><ResponsiveContainer width="100%" height="100%"><BarChart accessibilityLayer data={data.vaf_histogram}><XAxis dataKey="label" tick={{fill:"var(--muted)",fontSize:9}} interval={1}/><YAxis allowDecimals={false} width={40} tick={{fill:"var(--muted)",fontSize:10}}/><Tooltip contentStyle={tipStyle}/><Bar name="Observations" dataKey="count" fill="var(--accent)" radius={[3,3,0,0]} isAnimationActive={false}/></BarChart></ResponsiveContainer></div><details className="histogram-values"><summary>View histogram values</summary><dl>{data.vaf_histogram.map(b=><div key={b.label}><dt>{b.label}</dt><dd>{b.count}</dd></div>)}</dl></details></section></>}
 {mode!=="Variant explorer"&&<section className="panel explorer-table"><div className="section-title"><div><h2>Gene explorer</h2><p>{data.genes.length} genes meet the ranking filter. Select a symbol to inspect its available metadata.</p></div></div><Table><TableHeader><TableRow>{["Gene","Matching samples","Eligible samples","Frequency","Unique variants","Observed chromosomes"].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{data.genes.length?data.genes.map(g=><TableRow key={g.id}><TableCell><button className="table-link" onClick={()=>setSelectedGene(g.symbol)}>{g.symbol}</button></TableCell><TableCell>{g.mutated_samples}</TableCell><TableCell>{g.eligible_samples}</TableCell><TableCell>{percent(g.frequency)}</TableCell><TableCell>{g.variants}</TableCell><TableCell>{g.observed_chromosomes.join(", ")||"No matching loci"}</TableCell></TableRow>):<TableRow><TableCell colSpan={6}>No genes match. Reset filters or lower the minimum sample count.</TableCell></TableRow>}</TableBody></Table>
 {gene&&<div className="record-detail" aria-label={gene.symbol+" gene details"}><div className="section-title"><h3>{gene.symbol} · Entrez {gene.id}</h3><button className="icon-button" aria-label="Close gene details" onClick={()=>setSelectedGene(null)}><X size={18}/></button></div><dl className="detail-grid"><div><dt>Gene type</dt><dd>{gene.gene_type}</dd></div><div><dt>Full name / gene coordinates</dt><dd>Not supplied by this snapshot</dd></div><div><dt>Observed cohort disease</dt><dd>{data.options.diseases.filter(([id])=>!filters.disease||id===filters.disease).map(([,name])=>name).join(", ")||"No eligible cohort"}</dd></div><div><dt>Pathways / drug targets</dt><dd>Not yet imported</dd></div></dl><p className="chart-caption">Observed chromosomes describe matching variant loci, not a gene’s genomic extent. Cohort disease context is not a gene–disease causality claim.</p><Button variant="outline" onClick={()=>drill(gene.symbol)}>Filter to {gene.symbol}<ArrowRight size={14}/></Button></div>}</section>}
 {mode!=="Gene explorer"&&<section className="panel explorer-table"><div className="section-title"><div><h2>Variant explorer</h2><p>{data.variants.total.toLocaleString()} unique variants · GRCh37 coordinates · select a locus for annotations</p></div><label className="sort-label">Sort variants<select value={filters.sort} onChange={e=>apply({...filters,sort:e.target.value,page:"1"})}><option value="position">Genomic position ↑</option><option value="position_desc">Genomic position ↓</option><option value="samples">Matching samples ↓</option></select></label></div><Table><TableHeader><TableRow>{["Locus · reference > alternate","Gene","Type","Samples","Tumour VAF range"].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{data.variants.items.length?data.variants.items.map(v=><TableRow key={v.variant_id}><TableCell><button className="table-link locus" onClick={()=>setSelectedVariant(v.variant_id)}>{locus(v)}</button></TableCell><TableCell>{v.genes.join(", ")||"Not annotated"}</TableCell><TableCell>{v.variant_type}</TableCell><TableCell>{v.samples}</TableCell><TableCell>{v.vaf_min===null?"Not measured":percent(v.vaf_min)+" – "+percent(v.vaf_max)}<small>{v.vaf_measured} measured observations</small></TableCell></TableRow>):<TableRow><TableCell colSpan={5}>No variants match these filters. Try another gene, locus or chromosome.</TableCell></TableRow>}</TableBody></Table>
 <div className="pagination-row" aria-label="Variant pagination"><label>Rows per page<select value={filters.page_size} onChange={e=>apply({...filters,page_size:e.target.value,page:"1"})}>{[10,25,50,100].map(n=><option key={n}>{n}</option>)}</select></label><span>Page {data.variants.page} of {Math.max(1,Math.ceil(data.variants.total/data.variants.page_size))}</span><Button variant="outline" aria-label="Previous variant page" disabled={data.variants.page<=1} onClick={()=>apply({...filters,page:String(data.variants.page-1)})}><ArrowLeft size={14}/></Button><Button variant="outline" aria-label="Next variant page" disabled={data.variants.page*data.variants.page_size>=data.variants.total} onClick={()=>apply({...filters,page:String(data.variants.page+1)})}><ArrowRight size={14}/></Button></div>
 {variant&&<div className="record-detail" aria-label="Variant details"><div className="section-title"><h3>{variant.assembly} · {locus(variant)}</h3><button className="icon-button" aria-label="Close variant details" onClick={()=>setSelectedVariant(null)}><X size={18}/></button></div><dl className="detail-grid"><div><dt>Source consequence</dt><dd>{variant.consequences.join(", ")||"Not supplied"}</dd></div><div><dt>Clinical significance</dt><dd>Not supplied; no clinical interpretation</dd></div><div><dt>Population allele frequency</dt><dd>Not supplied</dd></div><div><dt>Source database</dt><dd><a href={data.dataset.url} target="_blank" rel="noreferrer">{data.dataset.source}</a></dd></div></dl></div>}</section>}
 {mode==="Genomics"&&<section className="panel matrix-panel"><h2>Sample mutation matrix</h2><p className="body-copy">Filled cells indicate an observed matching SNV. Empty cells mean no matching observation, not confirmed wild type. “—” means the gene is outside the sample profile’s imported coverage.</p><div className="matrix-scroll"><table className="mutation-matrix"><caption>Genes by public coded sample identifiers, sorted by sample identifier</caption><thead><tr><th scope="col">Gene / sample</th>{data.heatmap.samples.map(s=><th scope="col" key={s}><span>{s}</span></th>)}</tr></thead><tbody>{data.heatmap.rows.map(row=><tr key={row.symbol}><th scope="row">{row.symbol}</th>{row.values.map((value,i)=><td key={i} className={value===1?"observed":value===null?"uncovered":"not-observed"} title={row.symbol+" · "+data.heatmap.samples[i]+": "+(value===1?"Observed SNV":value===null?"Outside coverage":"No matching observation")}><span className="sr-only">{value===1?"Observed SNV":value===null?"Outside coverage":"No matching observation"}</span>{value===null?"—":""}</td>)}</tr>)}</tbody></table></div>{!data.heatmap.rows.length&&<p className="body-copy">No genes meet the ranking filter.</p>}<div className="pagination-row"><span>Samples {data.heatmap.total?(data.heatmap.page-1)*40+1:0}–{Math.min(data.heatmap.page*40,data.heatmap.total)} of {data.heatmap.total}</span><Button variant="outline" aria-label="Previous sample page" disabled={data.heatmap.page<=1} onClick={()=>apply({...filters,heatmap_page:String(data.heatmap.page-1)})}><ArrowLeft size={14}/></Button><Button variant="outline" aria-label="Next sample page" disabled={data.heatmap.page*40>=data.heatmap.total} onClick={()=>apply({...filters,heatmap_page:String(data.heatmap.page+1)})}><ArrowRight size={14}/></Button></div></section>}
 <section className="analysis-method"><h2>Method & provenance</h2><p>Frequency = distinct samples with a matching imported variant in the gene / distinct samples in profiles covering that imported gene. Study and disease filters define the cohort. Variant filters affect the numerator. Minimum sample count affects only gene ranking and matrix rows.</p><ul>{data.limitations.map(l=><li key={l}>{l}</li>)}</ul><div className="checksum"><span>Dataset SHA-256</span><code>{data.dataset.sha256}</code></div><p>Computed {new Date(data.computed_at).toISOString()} · code <code>{data.code_revision.slice(0,12)}</code>. JSON exports include filters, method, source and checksum; variant and matrix rows contain only the displayed pages.</p></section>
 </>}
 </div>;
}
