"use client";
import {useEffect,useRef,useState} from "react";
import {ArrowLeft,ArrowRight,Download,FlaskConical,Play,RefreshCw} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Textarea} from "@/components/ui/textarea";
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from "@/components/ui/table";
type Meta={method:string;method_version:string;parameters:Record<string,string|number>;computed_at:string;code_revision:string;source:string;limitations:string[]};
type Input={length:number;sha256:string;sequence:string};
type Stats=Meta&{input:Input;known_bases:number;unknown_bases:number;gc_percent:number|null;at_percent:number|null;composition:{base:string;count:number;percent:number}[];kmers:{k:number;total_windows:number;valid_windows:number;excluded_windows:number;unique:number;items:{kmer:string;count:number;frequency:number}[]}};
type Alignment=Meta&{input_a:Input;input_b:Input;score:number;aligned_a:string;aligned_b:string;markers:string;columns:number;matches:number;mismatches:number;unknown_pairs:number;gap_columns:number;identity_percent:number|null;range_a:[number,number]|null;range_b:[number,number]|null;matrix:{scores:number[][]|null;path:[number,number][];row_bases:string;column_bases:string}};
const pct=(n:number|null)=>n===null?"Not defined":n.toFixed(2)+"%";
function saveJson(value:Stats|Alignment){const url=URL.createObjectURL(new Blob([JSON.stringify({kind:"sequence_analysis",...value},null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download="pharmagenome-sequence-"+("input" in value?"statistics":"alignment")+".json";a.click();URL.revokeObjectURL(url);}
function Editor({id,label,value,onChange,onError,disabled,limit}:{id:string;label:string;value:string;onChange:(s:string)=>void;onError:(s:string)=>void;disabled:boolean;limit:number}){
 async function upload(file:File|undefined){if(!file)return;if(file.size>limit){onError("File exceeds the "+limit.toLocaleString()+"-byte input limit.");return;}try{onChange(await file.text());}catch{onError("The file could not be read. Try a plain-text DNA or FASTA file.");}}
 return <div className="sequence-editor"><label htmlFor={id}>{label}</label><Textarea id={id} value={value} onChange={e=>onChange(e.target.value)} placeholder="Paste A/C/G/T/N bases or one FASTA record" maxLength={limit} spellCheck={false} autoCapitalize="off" autoCorrect="off" disabled={disabled}/><div className="editor-meta"><label className="sequence-upload">Upload {label.toLowerCase()}<input aria-label={"Upload "+label.toLowerCase()} type="file" accept=".txt,.fa,.fasta,.fna,text/plain" disabled={disabled} onChange={e=>{void upload(e.target.files?.[0]);e.target.value="";}}/></label><span>{value.length.toLocaleString()} input characters</span></div></div>;
}
export function SequenceTools(){
 const [tab,setTab]=useState<"statistics"|"align">("statistics");
 const [a,setA]=useState("");const [b,setB]=useState("");
 const [k,setK]=useState("3");const [mode,setMode]=useState("global");
 const [match,setMatch]=useState("2");const [mismatch,setMismatch]=useState("-1");const [gap,setGap]=useState("-2");
 const [result,setResult]=useState<Stats|Alignment|null>(null);const [error,setError]=useState<string|null>(null);const [busy,setBusy]=useState(false);
 const [example,setExample]=useState(false);const [kPage,setKPage]=useState(1);
 const active=useRef<AbortController|null>(null);
 useEffect(()=>()=>active.current?.abort(),[]);
 function clear(){setResult(null);setError(null);setKPage(1);}
 function changeA(s:string){clear();setA(s);setExample(false);}
 function changeB(s:string){clear();setB(s);setExample(false);}
 function switchTab(next:"statistics"|"align"){active.current?.abort();setBusy(false);clear();setTab(next);}
 function teaching(){clear();setExample(true);setA(tab==="statistics"?">teaching_example\nAACCGGTTNNACGTACGT":"ACGTACGT");setB("ACGTCGT");setK("2");setMatch("2");setMismatch("-1");setGap("-2");}
 async function run(){
  clear();const controller=new AbortController();active.current?.abort();active.current=controller;setBusy(true);
  try{const response=await fetch("/api/sequences/"+tab,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(tab==="statistics"?{sequence:a,k:Number(k)}:{sequence_a:a,sequence_b:b,mode,match:Number(match),mismatch:Number(mismatch),gap:Number(gap)}),signal:controller.signal});
   const body=await response.json();if(!response.ok)throw new Error(typeof body.detail==="string"?body.detail:"Check your sequence inputs.");
   if(!controller.signal.aborted)setResult(body);
  }catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:"Sequence computation failed. Try again.");}finally{if(!controller.signal.aborted)setBusy(false);}
 }
 const stats=result&&"input" in result?result:null;const alignment=result&&"aligned_a" in result?result:null;
 const path=new Set(alignment?.matrix.path.map(([i,j])=>i+","+j));
 return <div className="sequence-tools">
 <div className="sequence-tabs" role="tablist" aria-label="Sequence tools"><button id="statistics-tab" role="tab" aria-selected={tab==="statistics"} aria-controls="sequence-panel" tabIndex={tab==="statistics"?0:-1} onKeyDown={e=>{if(e.key==="ArrowRight"||e.key==="ArrowLeft"){e.preventDefault();switchTab("align");document.getElementById("align-tab")?.focus();}}} onClick={()=>switchTab("statistics")}>Sequence statistics</button><button id="align-tab" role="tab" aria-selected={tab==="align"} aria-controls="sequence-panel" tabIndex={tab==="align"?0:-1} onKeyDown={e=>{if(e.key==="ArrowRight"||e.key==="ArrowLeft"){e.preventDefault();switchTab("statistics");document.getElementById("statistics-tab")?.focus();}}} onClick={()=>switchTab("align")}>Pairwise alignment</button></div>
 <section id="sequence-panel" role="tabpanel" aria-labelledby={tab==="statistics"?"statistics-tab":"align-tab"} className="panel sequence-input-panel"><div className="section-title"><div><h2>{tab==="statistics"?"Understand a DNA sequence.":"Compare two DNA sequences."}</h2><p>{tab==="statistics"?"Composition and overlapping k-mers · up to 100,000 bases":"Needleman–Wunsch or Smith–Waterman · up to 1,000 bases per sequence"}</p></div><FlaskConical size={21}/></div>
 <form onSubmit={e=>{e.preventDefault();void run();}}><div className={tab==="align"?"sequence-editors paired":"sequence-editors"}><Editor id="sequence-a" label={tab==="statistics"?"DNA sequence":"Sequence A"} value={a} onChange={changeA} onError={message=>{clear();setError(message);}} disabled={busy} limit={tab==="statistics"?200000:5000}/>{tab==="align"&&<Editor id="sequence-b" label="Sequence B" value={b} onChange={changeB} onError={message=>{clear();setError(message);}} disabled={busy} limit={5000}/>}</div>
 <div className="sequence-settings">{tab==="statistics"?<label htmlFor="kmer-length">k-mer length<select id="kmer-length" aria-label="k-mer length" value={k} disabled={busy} onChange={e=>{clear();setK(e.target.value);}}>{[1,2,3,4,5,6].map(n=><option key={n}>{n}</option>)}</select></label>:<><label htmlFor="alignment-mode">Alignment method<select id="alignment-mode" aria-label="Alignment method" value={mode} disabled={busy} onChange={e=>{clear();setMode(e.target.value);}}><option value="global">Global · Needleman–Wunsch</option><option value="local">Local · Smith–Waterman</option></select></label><label htmlFor="match-score">Match reward<input id="match-score" type="number" required min="1" max="10" step="1" value={match} disabled={busy} onChange={e=>{clear();setMatch(e.target.value);}}/></label><label htmlFor="mismatch-score">Mismatch score<input id="mismatch-score" type="number" required min="-10" max="0" step="1" value={mismatch} disabled={busy} onChange={e=>{clear();setMismatch(e.target.value);}}/></label><label htmlFor="gap-score">Gap score per base<input id="gap-score" type="number" required min="-10" max="-1" step="1" value={gap} disabled={busy} onChange={e=>{clear();setGap(e.target.value);}}/></label></>}</div>
 <p className="sequence-help">Accepts A/C/G/T/N, lowercase and whitespace, or a single FASTA record. {tab==="align"?"N always receives the mismatch score; gaps use a linear penalty.":"GC/AT excludes N; k-mer windows containing N are counted separately."}</p><div className="sequence-actions"><Button type="submit" disabled={busy||!a.trim()||(tab==="align"&&!b.trim())}>{busy?<RefreshCw className="spin" size={15}/>:<Play size={15}/>} {busy?"Computing…":tab==="statistics"?"Calculate statistics":"Align sequences"}</Button><Button type="button" variant="outline" onClick={teaching} disabled={busy}>Load teaching example</Button><button type="button" className="text-action" disabled={busy} onClick={()=>{clear();setA("");setB("");setExample(false);}}>Clear inputs</button></div>{example&&<p className="example-note">Synthetic teaching example · not patient or reference-genome data</p>}
 </form><p className="sequence-privacy">Runs without a database or LLM. Inputs are sent to the research API for computation; the application does not save them to its database.</p></section>
 {busy&&<div className="sequence-pending" role="status">Computing from the submitted sequences…</div>}
 {error&&<section className="panel sequence-error" role="alert"><h2>Check the sequence request</h2><p>{error}</p><p>Edit the inputs or scoring values, then run the calculation again.</p></section>}
 {result&&<><div className="sequence-result-heading"><div><h2>{result.method}</h2><p>Computed from the normalized input · method v{result.method_version}</p></div><Button variant="outline" onClick={()=>saveJson(result)}><Download size={15}/>Export sequence JSON</Button></div>
 {stats&&<><section className="inventory sequence-inventory" aria-label="Sequence statistics results">{[["Sequence length",stats.input.length.toLocaleString()+" bp"],["Known bases",stats.known_bases.toLocaleString()],["Unknown N",stats.unknown_bases.toLocaleString()],["GC / known bases",pct(stats.gc_percent)],["AT / known bases",pct(stats.at_percent)]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</section><div className="sequence-result-grid"><section className="panel"><h2>Nucleotide composition</h2><p className="body-copy">Percentages use all {stats.input.length.toLocaleString()} bases, including N.</p><dl className="base-composition">{stats.composition.map(c=><div key={c.base}><dt>{c.base}</dt><dd><span className="base-track" aria-hidden="true"><i style={{width:c.percent+"%"}}/></span><strong>{c.count.toLocaleString()}</strong><span>{pct(c.percent)}</span></dd></div>)}</dl></section><section className="panel"><h2>Overlapping {stats.kmers.k}-mers</h2><p className="body-copy">{stats.kmers.valid_windows.toLocaleString()} valid windows / {stats.kmers.total_windows.toLocaleString()} possible windows. {stats.kmers.excluded_windows.toLocaleString()} excluded for N. Frequencies divide by valid windows; strands are not combined.</p><Table><TableHeader><TableRow><TableHead>k-mer</TableHead><TableHead>Count</TableHead><TableHead>Frequency</TableHead></TableRow></TableHeader><TableBody>{stats.kmers.items.length?stats.kmers.items.slice((kPage-1)*20,kPage*20).map(row=><TableRow key={row.kmer}><TableCell><code>{row.kmer}</code></TableCell><TableCell>{row.count.toLocaleString()}</TableCell><TableCell>{pct(row.frequency*100)}</TableCell></TableRow>):<TableRow><TableCell colSpan={3}>No valid windows. The sequence is shorter than k or all windows contain N.</TableCell></TableRow>}</TableBody></Table><div className="pagination-row"><span>Page {kPage} of {Math.max(1,Math.ceil(stats.kmers.unique/20))} · {stats.kmers.unique} unique</span><Button variant="outline" aria-label="Previous k-mer page" disabled={kPage<=1} onClick={()=>setKPage(kPage-1)}><ArrowLeft size={14}/></Button><Button variant="outline" aria-label="Next k-mer page" disabled={kPage*20>=stats.kmers.unique} onClick={()=>setKPage(kPage+1)}><ArrowRight size={14}/></Button></div></section></div></>}
 {alignment&&<><section className="inventory sequence-inventory" aria-label="Alignment results">{[["Alignment score",String(alignment.score)],["Exact matches",String(alignment.matches)],["Gap columns",String(alignment.gap_columns)],["Unknown pairs",String(alignment.unknown_pairs)],["Column identity",pct(alignment.identity_percent)]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</section><section className="panel alignment-panel"><h2>Alignment traceback</h2><p className="body-copy">{alignment.columns?alignment.columns+" columns · A "+alignment.range_a?.join("–")+" · B "+alignment.range_b?.join("–")+" (1-based, inclusive)":"No positive local alignment was found for these inputs and scores."}</p><p className="alignment-legend"><code>|</code> exact A/C/G/T match <code>.</code> mismatch <code>?</code> unknown N pair <code>–</code> gap</p>{alignment.columns>0&&<div className="alignment-scroll" tabIndex={0} role="region" aria-label="Aligned sequences, horizontally scrollable"><div className="alignment-blocks">{Array.from({length:Math.ceil(alignment.columns/50)},(_,i)=>{const start=i*50;return <div className="alignment-block" key={i}><small>Alignment columns {start+1}–{Math.min(start+50,alignment.columns)}</small><pre>{"A  "+alignment.aligned_a.slice(start,start+50)+"\n   "}{alignment.markers.slice(start,start+50).split("").map((c,j)=><span key={j} className={c==="|"?"alignment-match":c==="."?"alignment-mismatch":""}>{c}</span>)}{"\nB  "+alignment.aligned_b.slice(start,start+50)}</pre></div>;})}</div></div>}</section>
 <section className="panel score-matrix-panel"><h2>Dynamic-programming matrix</h2><p className="body-copy">Rows represent A and columns B. Highlighted cells trace the chosen optimum. Ties prefer diagonal, then up, then left; local alignment starts at the first highest score.</p>{alignment.matrix.scores?<div className="score-matrix-scroll" tabIndex={0} role="region" aria-label="Alignment score matrix, horizontally scrollable"><table className="score-matrix"><caption>Scores by consumed input prefix</caption><thead><tr><th scope="col">A / B</th><th scope="col">0</th>{alignment.matrix.column_bases.split("").map((base,j)=><th scope="col" key={j}>{base}<small>{j+1}</small></th>)}</tr></thead><tbody>{alignment.matrix.scores.map((row,i)=><tr key={i}><th scope="row">{i?alignment.matrix.row_bases[i-1]:"0"}{i>0&&<small>{i}</small>}</th>{row.map((score,j)=><td key={j} className={path.has(i+","+j)?"trace-cell":""} title={"A prefix "+i+", B prefix "+j+(path.has(i+","+j)?", traceback":"")}>{score}<span className="sr-only">{path.has(i+","+j)?" traceback":""}</span></td>)}</tr>)}</tbody></table></div>:<p className="matrix-limit">The alignment is complete. Matrix preview is limited to inputs of 20 bases each; use shorter inputs to inspect every score.</p>}</section></>}
 <section className="analysis-method"><h2>Method & input provenance</h2><ul>{result.limitations.map(l=><li key={l}>{l}</li>)}</ul>{(stats?[["Sequence",stats.input]]:alignment?[["Sequence A",alignment.input_a],["Sequence B",alignment.input_b]]:[]).map(([label,input])=><div className="checksum" key={String(label)}><span>{String(label)} SHA-256</span><code>{(input as Input).sha256}</code></div>)}<p>Computed {new Date(result.computed_at).toISOString()} · code <code>{result.code_revision.slice(0,12)}</code>. Export includes normalized inputs, complete k-mer results or alignment, scoring, checksums and method limitations. No reference-genome match or clinical significance is inferred.</p></section>
 </>}
 </div>;
}
