"use client";
import {useEffect,useRef,useState} from "react";
import {ArrowDown,ArrowRight,ArrowUpRight,BrainCircuit,Check,ChevronRight,Database,Dna,ExternalLink,FileJson,GitBranch,Layers,LayoutDashboard,LoaderCircle,Menu,Moon,Network,RefreshCw,ShieldCheck,Sun,X} from "lucide-react";
import {Statistics} from "@/components/statistics";
import {Modeling} from "@/components/modeling";
import {Research} from "@/components/research";
import {SequenceTools} from "@/components/sequences";
import {Genomics} from "@/components/genomics";
import {Button} from "@/components/ui/button";
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from "@/components/ui/table";

type Dataset = {id:number;name:string;source:string;version:string;retrieved_at:string;is_fixture:boolean;url:string;license:string;sha256:string;valid:number|null;invalid:number|null;duplicates:number|null;excluded:number|null;downloaded:number|null;report:{unit?:string;samples:number;genes:number;unique_variants:number;missing_vaf:number;coverage:string;method:string;exclusion_reasons:Record<string,number>;validation_reasons:Record<string,number>}|null;manifest:{kind?:string;assembly?:string;limitations:string[];snapshot_git_revision?:string}};
type System = {version:string;phase:number;checked_at:string;database:{status:string;schema_version:string|null};counts:Record<string,number>|null;datasets:Dataset[];limitations:string[]};
type View = "Workspace"|"Genomics"|"Gene explorer"|"Variant explorer"|"Sequence analysis"|"Research associations"|"Statistics"|"Drug response"|"Data sources"|"Architecture";
const repo="https://github.com/292akhil2929-cmyk/pharmagenome";
const sourcePlans = [
 {name:"cBioPortal",type:"Somatic variants · profiled cohorts",purpose:"Mutation observations and explicit sample denominators",url:"https://docs.cbioportal.org/web-api-and-clients/"},
 {name:"NCBI Gene",type:"Gene identifiers · genomic locations",purpose:"Stable gene identity and assembly-specific coordinates",url:"https://www.ncbi.nlm.nih.gov/gene/"},
 {name:"CellMiner",type:"NCI-60 · matched drug response and genomic features",purpose:"Aligned cell-line modeling with pinned source checksums",url:"https://discover.nci.nih.gov/cellminer/"},
 {name:"Open Targets",type:"Drug mechanisms · source research",purpose:"Versioned drug-target evidence and Reactome memberships",url:"https://platform.opentargets.org/"},
 {name:"ChEMBL",type:"Compounds · target evidence",purpose:"Sourced drug-target research relationships",url:"https://www.ebi.ac.uk/chembl/"},
 {name:"Reactome",type:"Curated biological pathways",purpose:"Gene membership for transparent pathway overlap",url:"https://reactome.org/"}
];
export function Workspace() {
 const [researchGene,setResearchGene]=useState("");
 const [view,setView]=useState<View>("Workspace");
 const [data,setData]=useState<System|null>(null);
 const [error,setError]=useState<string|null>(null);
 const [loading,setLoading]=useState(true);
 const [dark,setDark]=useState(false);
 const [menu,setMenu]=useState(false);
 const [mobile,setMobile]=useState(false);
 const sidebar=useRef<HTMLElement>(null);
 const menuTrigger=useRef<HTMLButtonElement>(null);
 useEffect(()=>{const mq=window.matchMedia("(max-width:650px)");const update=()=>{setMobile(mq.matches);if(!mq.matches)setMenu(false);};update();mq.addEventListener("change",update);return()=>mq.removeEventListener("change",update);},[]);
 useEffect(()=>{
  if(!menu||!mobile)return;
  const drawer=sidebar.current;
  const focusable=()=>Array.from(drawer?.querySelectorAll<HTMLElement>("a[href],button:not([disabled])")||[]);
  focusable()[0]?.focus();
  function handleKey(e:KeyboardEvent){
   if(e.key==="Escape"){e.preventDefault();setMenu(false);}
   if(e.key==="Tab"){const items=focusable();const first=items[0];const last=items[items.length-1];
    if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}
    else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}
   }
  }
  document.addEventListener("keydown",handleKey);
  const oldOverflow=document.body.style.overflow;document.body.style.overflow="hidden";
  return()=>{document.removeEventListener("keydown",handleKey);document.body.style.overflow=oldOverflow;menuTrigger.current?.focus();};
 },[menu,mobile]);
 useEffect(()=>{const value=localStorage.getItem("pharmagenome-theme")==="dark";setDark(value);document.documentElement.dataset.theme=value?"dark":"light";},[]);
 async function refresh() {
  setLoading(true);setError(null);
  try {const res=await fetch("/api/system",{cache:"no-store"});const body=await res.json();if(!res.ok) throw new Error(body.detail||"Connection failed.");setData(body);}
  catch(e){setData(null);setError(e instanceof Error?e.message:"Connection failed.");}
  finally{setLoading(false);}
 }
 useEffect(()=>{void refresh();},[]);
 function theme(){const value=!dark;setDark(value);document.documentElement.dataset.theme=value?"dark":"light";localStorage.setItem("pharmagenome-theme",value?"dark":"light");}
 function navigate(next:View){setView(next);setMenu(false);}
 const ready=data?.database.status==="ready";
 const imported=ready?data?.datasets.find(d=>d.manifest.assembly==="GRCh37"):undefined;
 const researchImported=ready?data?.datasets.find(d=>d.manifest.kind==="research_associations"):undefined;
 const label=loading?"Checking connection":error?"API unavailable":ready?"Database connected":data?.database.status==="not_configured"?"Database not configured":data?.database.status==="migration_required"?"Migration required":"Database unavailable";
 function exportSnapshot(){if(!data)return;const url=URL.createObjectURL(new Blob([JSON.stringify({kind:"system_snapshot",...data},null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download="pharmagenome-system-snapshot.json";a.click();URL.revokeObjectURL(url);}
 return <div className="shell">
  <a className="skip-link" href="#main">Skip to workspace</a>
  <aside ref={sidebar} id="research-navigation" inert={mobile&&!menu?true:undefined} role={mobile&&menu?"dialog":undefined} aria-modal={mobile&&menu?true:undefined} className={menu?"sidebar open":"sidebar"} aria-label="Workspace navigation">
   <a href="/" className="brand"><span className="brand-mark"><Dna size={24}/></span><span>PharmaGenome<span className="brand-sub">Genomics. In context.</span></span></a>
   <div className="workspace-selector"><span className="workspace-avatar">PG</span><div>Research workspace<small>Public research · v0.8</small></div><Layers size={16}/></div>
   <nav>{([{name:"Workspace",icon:LayoutDashboard},{name:"Genomics",icon:Dna},{name:"Gene explorer",icon:GitBranch},{name:"Variant explorer",icon:Layers},{name:"Sequence analysis",icon:Dna},{name:"Research associations",icon:Network},{name:"Statistics",icon:Layers},{name:"Drug response",icon:BrainCircuit},{name:"Data sources",icon:Database},{name:"Architecture",icon:Network}] as const).map(item=><button key={item.name} onClick={()=>navigate(item.name)} aria-current={view===item.name?"page":undefined}><item.icon size={18}/>{item.name}{view===item.name&&<ChevronRight size={15}/>}</button>)}</nav>
   <div className="sidebar-note"><GitBranch size={18}/><strong>A foundation for evidence.</strong><p>Every result begins with a dataset. Every relationship keeps its source.</p><a href={repo+"/blob/main/docs/ROADMAP.md"} target="_blank" rel="noreferrer">View the build roadmap <ArrowUpRight size={14}/></a></div>
   <div className="sidebar-bottom"><a href={repo} target="_blank" rel="noreferrer"><GitBranch size={16}/>Source code<ExternalLink size={13}/></a><span><ShieldCheck size={16}/>Research use only</span></div>
  </aside>
  {menu&&<button aria-label="Close navigation overlay" className="overlay" onClick={()=>setMenu(false)}/>}
  <div className="main-shell" inert={mobile&&menu?true:undefined}>
   <header className="topbar"><div className="breadcrumb"><button ref={menuTrigger} aria-expanded={menu} aria-controls="research-navigation" className="icon-button mobile-menu" aria-label={menu?"Close navigation":"Open navigation"} onClick={()=>setMenu(!menu)}>{menu?<X size={20}/>:<Menu size={20}/>}</button><span>Research workspace</span><ChevronRight size={14}/><strong>{view}</strong></div><div className="top-actions"><span className="release-chip">Evidence explanation release</span><button className="icon-button" aria-label={dark?"Switch to light mode":"Switch to dark mode"} onClick={theme}>{dark?<Sun size={19}/>:<Moon size={19}/>}</button><span className="profile">PG</span></div></header>
   <main id="main">
    <div className="page-heading"><div><h1>{view==="Workspace"?"Research starts with evidence.":view==="Data sources"?"Know where your data begins.":view==="Statistics"?"Ask a question. Quantify the uncertainty.":view==="Drug response"?"Model response. Keep the boundary visible.":view==="Research associations"?"Connect genes to research.":view==="Sequence analysis"?"Read the sequence. Trace the alignment.":view==="Genomics"?"Variation across your cohort.":view==="Gene explorer"?"Follow the evidence to a gene.":view==="Variant explorer"?"Inspect each genomic change.":"Built to make results traceable."}</h1><p>{view==="Workspace"?"Your genomic and pharmaceutical analytics workspace.":view==="Data sources"?"A transparent record of source, version, retrieval and quality.":view==="Statistics"?"Transparent hypothesis tests, paired correlations and source-scoped enrichment.":view==="Drug response"?"Cell-line response distributions, repeated validation and held-out explainability.":view==="Research associations"?"Trace drug mechanisms and pathway membership to their source.":view==="Sequence analysis"?"DNA composition and direct implementations of global and local alignment.":view==="Architecture"?"A computational pipeline with provenance at every step.":"Explore imported SNVs with explicit cohort denominators and source provenance."}</p></div><Button variant="outline" onClick={refresh} disabled={loading}>{loading?<LoaderCircle className="spin" size={16}/>:<RefreshCw size={16}/>}Refresh connection</Button></div>
    <div className={"connection-strip "+(error?"connection-error":"")} role="status"><span className={"status-dot "+(ready?"ready":"")}/><strong>{label}</strong><span>{loading?"Contacting the research API…":error|| (ready?"PostgreSQL is responding. Dataset counts are read from the database.":"Dataset counts remain unavailable until the database is ready.")}</span>{data&&<time dateTime={data.checked_at}>{new Date(data.checked_at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</time>}</div>
    {(view==="Genomics"||view==="Gene explorer"||view==="Variant explorer")&&<Genomics mode={view} datasets={data?.datasets.filter(d=>d.manifest.assembly==="GRCh37")??[]} onResearch={symbol=>{setResearchGene(symbol);navigate("Research associations");}}/>}
    {view==="Statistics"&&<Statistics/>}
    {view==="Drug response"&&<Modeling/>}
    {view==="Sequence analysis"&&<SequenceTools/>}
    {view==="Research associations"&&<Research initialGene={researchGene}/>}
    {view==="Workspace"&&<>
     <section className="inventory" aria-label="Dataset inventory">{["samples","variants","genes","drugs","pathways"].map((key)=><div key={key}><span>{key==="samples"?"Total samples":key==="genes"?"Catalogued genes":key==="variants"?"Unique variants":key==="drugs"?"Compounds":"Pathways"}</span><strong>{data?.counts?data.counts[key].toLocaleString():"—"}</strong><small>{data?.counts?"Records in database":"Awaiting connection"}</small></div>)}</section>
     <div className="primary-grid">
      <section className="panel cohort-panel"><div className="section-title"><div><h2>Your research collection</h2><p>Source snapshots and their declared research scope.</p></div><Database size={20}/></div>{imported?<div className="cohort-content"><div className="cohort-tags"><span>{imported.is_fixture?"Development fixture":"Public source data"}</span><span>{imported.manifest.assembly}</span></div><h3>{imported.name}</h3><p>{imported.report?.coverage}. Profile membership includes samples without an accepted observation; it does not confirm a wild-type genotype.</p><dl className="cohort-facts"><div><dt>Sample observations</dt><dd>{imported.valid?.toLocaleString()??"—"}</dd></div><div><dt>Distinct SNV identities</dt><dd>{imported.report?.unique_variants.toLocaleString()??"—"}</dd></div></dl><div className="report-actions"><Button onClick={()=>navigate("Genomics")}>Explore genomic data <ArrowRight size={16}/></Button><button className="text-action" onClick={()=>navigate("Data sources")}>Inspect import & provenance</button></div></div>:<div className="empty-collection"><div className="empty-symbol"><Database size={30}/><span><Layers size={14}/></span></div><h3>{!ready?(loading?"Checking your collection…":"Collection unavailable."):data?.datasets.length?"Your datasets are ready to inspect.":"No datasets imported yet."}</h3><p>{!ready?"A database connection is required to confirm the contents of your research collection.":data?.datasets.length?"Open the data catalogue to review provenance and ingestion status.":"The workspace is ready for its first scientific dataset. Counts, visualizations and findings will come from validated records."}</p><Button onClick={()=>navigate("Data sources")}>Explore data sources <ArrowRight size={16}/></Button></div>}<div className="collection-footer"><ShieldCheck size={16}/><span>No generated measurements. No implied clinical validity.</span></div></section>
      <section className="panel relationship-panel"><div className="section-title"><div><h2>From variation to context</h2><p>The research model</p></div><Network size={20}/></div><div className="relationship-flow">{[{name:"Genomic variation",detail:"Assembly · locus · alleles",icon:Dna},{name:"Genes & disease",detail:"Cohort · annotation · phenotype",icon:GitBranch},{name:"Pathways & targets",detail:"Membership · overlap · evidence",icon:Network},{name:"Pharmaceutical context",detail:"Compound · mechanism · source",icon:Layers}].map((item,i)=><div className="flow-step" key={item.name}><span className="flow-icon"><item.icon size={20}/></span><div><strong>{item.name}</strong><small>{item.detail}</small></div>{i<3&&<ArrowDown className="flow-arrow" size={15}/>}</div>)}</div><p className="model-note">Gene-level mechanisms and pathway membership are source associations; they do not establish variant-specific drug response.</p>{researchImported&&<Button variant="outline" onClick={()=>navigate("Research associations")}>Explore research associations <ArrowRight size={15}/></Button>}</section>
     </div>
     <div className="secondary-grid"><section className="panel"><div className="section-title"><div><h2>Dataset health</h2><p>Quality is measured, never assumed.</p></div><ShieldCheck size={20}/></div>{imported?<div className="health-summary"><dl>{[["Accepted",imported.valid],["Excluded",imported.excluded],["Invalid",imported.invalid],["Duplicates",imported.duplicates]].map(([name,count])=><div key={name}><dt>{name}</dt><dd>{typeof count==="number"?count.toLocaleString():"—"}</dd></div>)}</dl><p>{imported.downloaded?.toLocaleString()} source records reconciled. Exclusions reflect import scope, not failed validation.</p></div>:<div className="health-empty"><span>Validation coverage</span><strong>Not measured</strong><p>A completed ingestion report is required before quality percentages can be calculated.</p></div>}<button className="text-action" onClick={()=>navigate("Data sources")}>Review the quality report <ArrowUpRight size={16}/></button></section><section className="panel"><div className="section-title"><div><h2>Reproducibility, by design</h2><p>Inspect the foundation behind the workspace.</p></div><FileJson size={20}/></div><ul className="evidence-list"><li><Check size={16}/>Versioned datasets and source checksums</li><li><Check size={16}/>Explicit cohort and genome assembly</li><li><Check size={16}/>Analysis parameters and code revision</li></ul><Button variant="outline" onClick={exportSnapshot} disabled={!data||loading}><FileJson size={15}/>Export system snapshot</Button><small className="export-note">Exports infrastructure state, not an analytical result.</small></section></div>
    </>}
    {view==="Data sources"&&<><section className="panel source-panel"><div className="section-title"><div><h2>Imported datasets</h2><p>{ready?data?.datasets.length: "Unknown"} registered versions · source metadata stays with each import</p></div><Database size={20}/></div><Table><TableHeader><TableRow><TableHead>Dataset</TableHead><TableHead>Source</TableHead><TableHead>Version</TableHead><TableHead>Retrieved</TableHead><TableHead>Data type</TableHead></TableRow></TableHeader><TableBody>{data?.datasets.length?data.datasets.map(d=><TableRow key={d.id}><TableCell>{d.name}</TableCell><TableCell><a href={d.url}>{d.source}</a></TableCell><TableCell><code title={d.version}>{d.version.slice(0,12)}</code></TableCell><TableCell>{new Date(d.retrieved_at).toLocaleDateString()}</TableCell><TableCell>{d.is_fixture?"Development fixture":"Source data"}</TableCell></TableRow>):<TableRow><TableCell colSpan={5}><div className="table-empty">{ready?"No imports to report.":loading?"Checking imported datasets…":"Imported dataset inventory unavailable."}<span>{ready?"Data-source plans below are not ingested datasets.":"Refresh the connection to verify whether datasets have been imported."}</span></div></TableCell></TableRow>}</TableBody></Table></section>{data?.datasets.map(d=><DatasetReport key={d.id} dataset={d}/>)}<h2 className="standalone-title">Source connections</h2><div className="source-list">{sourcePlans.map((s)=><a href={s.url} key={s.name} target="_blank" rel="noreferrer"><div><h3>{s.name}</h3><span>{s.type}</span></div><p>{s.purpose}</p><span className="planned-chip">{(s.name==="cBioPortal"&&imported)||(s.name==="CellMiner"&&data?.datasets.some(d=>d.manifest.kind==="drug_response_modeling"))||(s.name==="Open Targets"&&researchImported)||(s.name==="Reactome"&&researchImported)||(s.name==="ChEMBL"&&researchImported)?"Imported subset":"Planned"}</span><ArrowUpRight size={18}/></a>)}</div><p className="source-footnote">Access terms, fields, retrieval dates and dataset versions must be recorded before import. <a href={repo+"/blob/main/DATA_SOURCES.md"}>Read the source policy <ArrowUpRight size={13}/></a></p></>}
    {view==="Architecture"&&<><section className="panel architecture-panel"><div className="section-title"><div><h2>Computation comes first.</h2><p>The optional explanation layer only receives computed, structured evidence.</p></div><GitBranch size={22}/></div><ol className="pipeline">{["Source snapshot","Validation & normalization","PostgreSQL analytical datasets","Statistics & bioinformatics","Model evaluation","Visualization & export","Optional research explanation"].map((step,i)=><li key={step}><span>{String(i+1).padStart(2,"0")}</span><div><strong>{step}</strong><small>{i<3?"Implemented":i===3?"Phase 7 · genomics, sequences and statistical inference":i===4?"Phase 7 · repeated stratified drug-response validation":i===5?"Phase 7 · complete analytical exports":"Planned in subsequent phases"}</small></div>{i<6&&<ArrowDown size={17}/>}</li>)}</ol></section><div className="secondary-grid"><section className="panel"><h2>Correct denominators</h2><p className="body-copy">Profile membership includes eligible samples with no observed mutations. Mutation frequency will count distinct mutated samples, not variant rows.</p></section><section className="panel"><h2>Separate observation from identity</h2><p className="body-copy">Genome assembly is part of every variant identity. Sample allele fractions remain separate from population frequencies and clinical annotations.</p></section></div><a className="text-action architecture-link" href={repo+"/blob/main/ARCHITECTURE.md"} target="_blank" rel="noreferrer">Read the full architecture <ArrowUpRight size={16}/></a></>}
    <footer><ShieldCheck size={17}/><p>This platform is intended for educational, research, and analytical purposes. Results are not medical advice and should not be used to diagnose disease or make treatment decisions.</p><a href={repo+"/blob/main/docs/ROADMAP.md"}>Phase 7 / 10 <ArrowUpRight size={13}/></a></footer>
   </main>
  </div>
 </div>;
}

function DatasetReport({dataset:d}:{dataset:Dataset}){
 const [busy,setBusy]=useState(false);
 const [error,setError]=useState<string|null>(null);
 async function download(){
  setBusy(true);setError(null);
  try{const response=await fetch("/api/datasets/"+d.id+"/report",{cache:"no-store"});
   if(!response.ok)throw new Error("Report unavailable. Please try again.");
   const report=await response.json();const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:"application/json"}));
   const a=document.createElement("a");a.href=url;a.download="pharmagenome-dataset-"+d.id+"-report.json";a.click();URL.revokeObjectURL(url);
  }catch{setError("Report unavailable. Please try again.");}finally{setBusy(false);}
 }
 return <section className="panel report-panel" aria-label={d.name+" quality report"}><div className="section-title"><div><h2>Import quality & provenance</h2><p>{d.name} · {d.is_fixture?"Synthetic development fixture":"Public research data"}</p></div><ShieldCheck size={20}/></div><dl className="report-counts">{[["Downloaded",d.downloaded],[d.manifest.kind==="research_associations"?"Accepted target links":"Accepted observations",d.valid],["Excluded",d.excluded],["Invalid",d.invalid],["Duplicates",d.duplicates]].map(([name,count])=><div key={name}><dt>{name}</dt><dd>{typeof count==="number"?count.toLocaleString():"—"}</dd></div>)}</dl><p className="body-copy">{d.manifest.kind==="research_associations"?"Accepted records are source drug-target links with a mechanism mapping to the selected gene. Clinical reports are research records, not independent studies or efficacy evidence.":"Accepted observations are sample–variant pairs. A variant observed in multiple samples contributes multiple observations. Excluded records fall outside this import’s scope."}</p>
 {d.report&&<div className="report-details"><div><h3>Validation record</h3><dl className="provenance-list"><div><dt>Method</dt><dd>{d.report.method}</dd></div><div><dt>Excluded by reason</dt><dd>{Object.entries(d.report.exclusion_reasons??{}).map(([reason,count])=>reason.replaceAll("_"," ") + ": " + count).join("; ")||"None"}</dd></div><div><dt>Invalid by reason</dt><dd>{Object.entries(d.report.validation_reasons??{}).map(([reason,count])=>reason + ": " + count).join("; ")||"None"}</dd></div>{d.manifest.kind!=="research_associations"&&<div><dt>Missing tumour VAF</dt><dd>{d.report.missing_vaf}</dd></div>}<div><dt>Retrieved</dt><dd><time dateTime={d.retrieved_at}>{new Date(d.retrieved_at).toISOString()}</time></dd></div></dl></div><div><h3>Scope & limitations</h3><ul className="limitations">{d.manifest.limitations.map(item=><li key={item}>{item}</li>)}</ul></div></div>}
 <div className="checksum"><span>Snapshot SHA-256</span><code>{d.sha256}</code></div><p className="source-footnote">{d.license} {d.manifest.kind==="research_associations"?"Target identity uses Ensembl symbol mapping; pathway membership comes from Reactome via Open Targets.":"Assembly bounds use Ensembl GRCh37 metadata."} <a href={repo+"/blob/main/DATA_SOURCES.md"} target="_blank" rel="noreferrer">Source documentation</a></p><div className="report-actions"><Button variant="outline" onClick={download} disabled={busy}>{busy?<LoaderCircle size={15} className="spin"/>:<FileJson size={15}/>}Download quality report</Button>{d.manifest.snapshot_git_revision&&/^[a-f0-9]{40}$/.test(d.manifest.snapshot_git_revision)&&<a className="text-action" href={repo+"/tree/"+d.manifest.snapshot_git_revision+"/backend/data/"+(d.manifest.kind==="research_associations"?"research_associations":"luad_snv")} target="_blank" rel="noreferrer">Inspect raw snapshot <ArrowUpRight size={15}/></a>}</div>{error&&<p className="report-error" role="alert">{error}</p>}
 </section>;
}
